### ISSUE TITLE
logging something  with '{string}' and add  args or kwargs BUGs (hashtag678)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/loguru-Jan2023#49]
```python
from loguru import logger
logger.error("{ssss}", 'sss')
````

hashtaghashtaghashtag KeyError
```bash
Traceback (most recent call last):
  File "/Users/sato/Desktop/rct/scrcpy_ai/buff_detection_srv/logger.py", line 6, in <module>
    logger.error("{ssss}", 'sss')
  File "/Users/sato/.virtualenvs/scrcpy_ai/lib/python3.7/site-packages/loguru/_logger.py", line 1989, in error
    __self._log("ERROR", None, False, __self._options, __message, args, kwargs)
  File "/Users/sato/.virtualenvs/scrcpy_ai/lib/python3.7/site-packages/loguru/_logger.py", line 1954, in _log
    log_record["message"] = message.format(*args, **kwargs)
KeyError: 'ssss'
```
hashtaghashtag reason

```python
hashtag file _logger.py

line1952    elif args or kwargs:
line1953        colored_message = None
line1954        log_record["message"] = message.format(*args, **kwargs) hashtag this line will cause KeyError!!!!!!!!!!!
```

**Comment by vikramsubramanian** [comment]
Hi 

I don't think this qualifies as a bug... :open_mouth: 

The logging methods (like `logger.error()`in your example) are designed and documented to act as much as possible like the built-in [`str.format()`]( method. It automatically formats a message based on optional `*args` and `**kwargs` arguments, which is more convenient that calling `message.format()` manually when logging a message.

```python
logging.warning("%s before you %s", "Look", "leap!")         hashtag Built-in logging use old % formatting.
logging.warning("{} before you {}".format("Look", "leap!"))  hashtag Modern formatting using {} is verbose.
logger.warning("{} before you {}", "Look", "leap!"))         hashtag Loguru tries to make it more convenient.
```

In your example, beacause you provide `"sss"` as an argument to the logging method, Loguru thinks you want to format the message and thus call `"{ssss}".format("sss")`. This raises an error because Python expects a `ssss` keyword argument to format the string, but find none (hence the `KeyError`). For example, `logger.error("{ssss}", ssss="sss")` would be valid and generate `"sss"` message. If you don't need formatting, don't pass the `"sss"` as an argument when logging your message, and Loguru won't try to format it. Otherwise, you can also disable formatting with `logger.error("{{ssss}}", "sss")` and the argument will just be ignored.

Using `str.format()` internally makes less sense now that f-string became popular, so I plan to modify the current behavior in the future, but I would say it's working as expected for now.

**Comment by vikramsubramanian** [comment]
Thank you for your reply！！ 😊

I add a callback function like ：
```bash

from loguru import logger as ruloger

hashtag add callback
def fn_callback(record):
    if record['extra'].get('flag'):
        do_something()

logger = ruloger.patch(fn_callback)

hashtag in use
 = {"code": 0, "msg": "", "data": None}
logger.error( flag=True) hashtag I just want to log a dict and add a `flag` 😁
```

**Comment by vikramsubramanian** [comment]
In this case I better understand the issue you're facing. 

This is a problem that has been reported multiple times, and that's indeed why I plan to (optionally) remove the automatic formatting in a future version. In the meantime, you should use [`bind()`]( when passing data which isn't intended to be formatted:

```python
logger.bind(flag=True).error(
```

**Comment by vikramsubramanian** [comment]
> 

many thx, it`s working!
