### ISSUE TITLE
Set extra record cause "KeyError" issue in FastAPI (hashtag676)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/loguru-Jan2023#50]
When i set some extra record in fastAPI startup event caused something error
hashtaghashtaghashtag Versions:
- python 3.8.12
- loguru 0.6.0
- fastapi 0.75
--- 
hashtaghashtaghashtag Code:
```
def logger_init():
    logger.remove()
    logger.add(
        sys.stdout,
        format="{extra[event]}",
    )
   context_logger = logger.bind(event="access")
   return context_logger

app = FastAPI()

async def startup_event():
    logger = logger_init()
    logger.info("Start up")
       

```
---
hashtaghashtaghashtag Error message : 
```
--- Logging error in Loguru Handler hashtag1 ---
Record was: {'elapsed': datetime.timedelta(microseconds=270683), 'exception': None, 'extra': {}, 'file': (name='__init__.py', path='/app/./app/__init__.py'), 'function': 'startup_event', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 100, 'message': '--- Startup Event ---', 'module': '__init__', 'name': 'app', 'process': (id=229, name='SpawnProcess-102'), 'thread': (id=139944207652672, name='MainThread'), 'time': datetime(2022, 7, 6, 14, 51, 4, 487669, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/loguru/_handler.py", line 155, in emit
    formatted = precomputed_format.format_map(formatter_record)
KeyError: 'event'
--- End of logging error ---
```

**Comment by vikramsubramanian** [comment]
> When i set some extra record in fastAPI startup event caused something error
> 
> hashtaghashtaghashtag Versions:
> * python 3.8.12
> * loguru 0.6.0
> * fastapi 0.75
> 
> hashtaghashtaghashtag Code:
> ```
> def logger_init():
>     logger.remove()
>     logger.add(
>         sys.stdout,
>         format="{extra[event]}",
>     )
>    context_logger = logger.bind(event="access")
>    return context_logger
> 
> app = FastAPI()
> 
> async def startup_event():
>     logger = logger_init()
>     logger.info("Start up")
>        
> ```
> 
> hashtaghashtaghashtag Error message :
> ```
> --- Logging error in Loguru Handler hashtag1 ---
> Record was: {'elapsed': datetime.timedelta(microseconds=270683), 'exception': None, 'extra': {}, 'file': (name='__init__.py', path='/app/./app/__init__.py'), 'function': 'startup_event', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 100, 'message': '--- Startup Event ---', 'module': '__init__', 'name': 'app', 'process': (id=229, name='SpawnProcess-102'), 'thread': (id=139944207652672, name='MainThread'), 'time': datetime(2022, 7, 6, 14, 51, 4, 487669, tzinfo=datetime.timezone(datetime.timedelta(0), 'UTC'))}
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/loguru/_handler.py", line 155, in emit
>     formatted = precomputed_format.format_map(formatter_record)
> KeyError: 'event'
> --- End of logging error ---
> ```
hashtaghashtaghashtag Yes it is a bug!!!
```python

from loguru import logger
logger.error("{qwer}", 'sss'). hashtag when you log something with `{}` and add somthing string in it, it can make KeyError
hashtag why?
hashtag file   _logger.py

line 1952        elif args or kwargs:
line 1953             colored_message = None
line 1954             log_record["message"] = message.format(*args, **kwargs) hashtag This is why there are bugs


```

**Comment by vikramsubramanian** [comment]
The issue is different from the one reported by 

 I'm unable to reproduce your error. The message is correctly printed on my terminal when I run `uvicorn main:app`. Please can you provide a fully reproducible example including all steps required to reproduce this issue?

**Comment by vikramsubramanian** [comment]
Here you are !
---
- python : 3.8.12
- loguru : 0.6.0
- fastapi : 0.75
- uvicorn : 0.18.2
---
Example : 
```
import sys
from loguru import logger
from fastapi import FastAPI


def logger_init() -> logger:
    logger.remove()
    logger.info("Initalize log formater ...")
    logger.add(
        sys.stderr,
        format="{extra[provider]} | {message}",
    )
    context_logger = logger.bind(provider="fastapi")
    return context_logger


def create_app():
    app = FastAPI()
    hashtag logger_init()
    app.context_logger = logger_init()

    
    async def startup_event():
        logger.info("--- Startup event without context logger---")     hashtag Error
        hashtag app.context_logger.info("--- Startup event with context logger---")   hashtag Correct


    return app


app = create_app()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", port=5000, log_level="info", reload=True)

```
---
Error message : 
```
--- Logging error in Loguru Handler hashtag2 ---
Record was: {'elapsed': datetime.timedelta(microseconds=83700), 'exception': None, 'extra': {}, 'file': (name='main.py', path='/home/eddiepai/WorkSpace/SideProject/LoguruIssue/main.py'), 'function': 'startup_event', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 24, 'message': '--- Startup Event ---', 'module': 'main', 'name': 'main', 'process': (id=15989, name='SpawnProcess-1'), 'thread': (id=139932065460864, name='MainThread'), 'time': datetime(2022, 7, 11, 21, 0, 16, 919912, tzinfo=datetime.timezone(datetime.timedelta(seconds=28800), 'CST'))}
Traceback (most recent call last):
  File "/home/eddiepai/.cache/pypoetry/virtualenvs/loguruissue-KCSHvFDy-py3.8/lib/python3.8/site-packages/loguru/_handler.py", line 155, in emit
    formatted = precomputed_format.format_map(formatter_record)
KeyError: 'provider'
--- End of logging error ---
```

**Comment by vikramsubramanian** [comment]
Thanks for the fully reproducible example.

The `provider` value is only present in the logger object returned by `.bind()`. The `extra` dict of default `logger` is empty, which causes a `KeyError` during formatting. You can set a default value with `logger.configure(extra={"provider": None})` for example.

**Comment by vikramsubramanian** [comment]
Thanks a lot. It works.
I have another question about formatting. If I  want to add additional metadata, **not in extra** records like ECS example
How can i do that ?
hashtaghashtaghashtag ECS Example code
```
import logging
import ecs_logging

hashtag Get the Logger
logger = logging.getLogger("app")
logger.setLevel(logging.DEBUG)

hashtag Add an ECS formatter to the Handler
handler = logging.StreamHandler()
handler.setFormatter(ecs_logging.StdlibFormatter())
logger.addHandler(handler)

hashtag Emit a log!
logger.debug("Example message!", extra={" "get"})
```
hashtaghashtaghashtag ECS  Output
```
{
    " "2020-03-20T18:11:37.895Z",
    "log.level": "debug",
    "message": "Example message!",
    "ecs": {
        "version": "1.6.0"
    },
    " {
      "request": {
        "method": "get"
      }
    },
    "log": {
        "logger": "app",
        "origin": {
            "file": {
                "line": 14,
                "name": "test.py"
            },
            "function": "func"
        },
        "original": "Example message!"
    }
}
```

**Comment by vikramsubramanian** [comment]
Can you use the `bind()` method again? Like so:

```python
logger.bind( message!")
```

**Comment by vikramsubramanian** [comment]
Alternatively, you can take a look at the [`patch()`]( method which gives more control (as you can access the entire `record`).

**Comment by vikramsubramanian** [comment]
Yap! It can add in extra key record. But I want to add **outside** the extra key.
hashtaghashtaghashtag For example:
```
logger.add(sys.stderr, format="{event[dataset]} {extra[provider]}")
logger.bind(event="login", provider="api")
```
hashtaghashtaghashtag Expected output:
```
{
 "event": "login",
 "extra": {
     "provider": "api"
  }
}
```

**Comment by vikramsubramanian** [comment]
Use the `patch()` function then:

```python
logger.patch(lambda record: record.update(event="login")).debug("Example message!")
```
